# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch
import torch

# Create random tensor
x = torch.rand(7,7)
print(f"random tensor x:\n {x}")
print(f"x's shape: {x.shape}")

random tensor x:
 tensor([[0.2290, 0.3617, 0.3709, 0.6532, 0.1315, 0.2009, 0.9977],
        [0.3121, 0.8360, 0.9023, 0.0386, 0.9343, 0.0302, 0.9712],
        [0.7598, 0.8045, 0.2558, 0.5525, 0.0790, 0.4237, 0.7821],
        [0.1091, 0.1368, 0.6412, 0.0660, 0.8662, 0.5755, 0.7243],
        [0.8316, 0.5883, 0.6583, 0.2246, 0.4479, 0.9833, 0.7643],
        [0.0158, 0.8171, 0.3652, 0.4935, 0.9077, 0.4085, 0.0574],
        [0.6372, 0.4634, 0.2565, 0.9088, 0.3915, 0.7723, 0.8700]])
x's shape: torch.Size([7, 7])


### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [3]:
# Create another random tensor
y = torch.rand(1,7)
print(f"y:\n {y}")

# Perform matrix multiplication 
result = x @ y.T 
print(f"x ({x.shape}) @ y.T ({y.T.shape}) --> {result.shape}")
print(f"result: {result}")

y:
 tensor([[0.5537, 0.2195, 0.8248, 0.6679, 0.5250, 0.6986, 0.4581]])
x (torch.Size([7, 7])) @ y.T (torch.Size([7, 1])) --> torch.Size([7, 1])
result: tensor([[1.6149],
        [2.0828],
        [1.8731],
        [1.8520],
        [2.5547],
        [1.6072],
        [2.4167]])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [4]:
import torch 

# Set manual seed
torch.manual_seed(0)

# Create two random tensors
x = torch.rand(7,7)
y = torch.rand(1,7)

# Matrix multiply tensors
result = torch.matmul(x,y.T)
print(result, result.shape)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]]) torch.Size([7, 1])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [5]:
import torch 

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"

# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [6]:
# Set random seed
torch.manual_seed(1234)

# Create two random tensors on GPU
x = torch.rand(2,3).to(device)
y = torch.rand(2,3).to(device)
print(f"x:\n {x}")
print(f"y:\n {y}")

x:
 tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')
y:
 tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [7]:
# Perform matmul on x and y 
result = torch.mm(x,y.T)
print(f"x @ y :\n {result}")

x @ y :
 tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')


### 8. Find the maximum and minimum values of the output of 7.

In [8]:
# Find max
print(f"max in result : {torch.max(result)}")

# Find min
print(f"min in result : {torch.min(result)}")

max in result : 0.5617256760597229
min in result : 0.3647301495075226


### 9. Find the maximum and minimum index values of the output of 7.

In [9]:
# Find arg max
print(f"argmax in result : {torch.argmax(result)}")

# Find arg min
print(f"argmin in result : {torch.argmin(result)}")


argmax in result : 3
argmin in result : 0



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [10]:
# Set seed
torch.manual_seed(7)

# Create random tensor
random_tensor = torch.rand(1,1,1,10)
print(random_tensor, random_tensor.shape)

# Remove single dimensions
squeezed_tensor = random_tensor.squeeze()
print(squeezed_tensor, squeezed_tensor.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
