# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



### 2. Create a random tensor with shape `(7, 7)`.


In [1]:
# Import torch
import torch

# Create random tensor
x = torch.rand(7,7)
print(f"random tensor x:\n {x}")
print(f"x's shape: {x.shape}")

random tensor x:
 tensor([[0.6585, 0.6246, 0.7033, 0.5537, 0.4633, 0.0746, 0.4449],
        [0.3008, 0.9000, 0.1162, 0.6409, 0.6054, 0.4753, 0.2969],
        [0.2717, 0.5480, 0.2586, 0.7424, 0.8416, 0.1262, 0.9941],
        [0.3794, 0.6042, 0.0639, 0.3012, 0.6816, 0.6296, 0.7001],
        [0.8899, 0.2781, 0.7030, 0.1497, 0.5769, 0.6498, 0.7579],
        [0.4284, 0.9510, 0.6184, 0.0693, 0.0712, 0.9228, 0.1278],
        [0.4492, 0.6728, 0.3052, 0.5883, 0.8318, 0.8253, 0.6128]])
x's shape: torch.Size([7, 7])


### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [2]:
# Create another random tensor
y = torch.rand(1,7)
print(f"y:\n {y}")

# Perform matrix multiplication 
result = x @ y.T 
print(f"x ({x.shape}) @ y.T ({y.T.shape}) --> {result.shape}")
print(f"result: {result}")

y:
 tensor([[0.4918, 0.8897, 0.3669, 0.0133, 0.1673, 0.8931, 0.6243]])
x (torch.Size([7, 7])) @ y.T (torch.Size([7, 1])) --> torch.Size([7, 1])
result: tensor([[1.5668],
        [1.7109],
        [1.5999],
        [1.8651],
        [2.0950],
        [2.2005],
        [2.1981]])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [3]:
import torch 

# Set manual seed
torch.manual_seed(0)

# Create two random tensors
x = torch.rand(7,7)
y = torch.rand(1,7)

# Matrix multiply tensors
result = torch.matmul(x,y.T)
print(result, result.shape)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]]) torch.Size([7, 1])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [4]:
# Set random seed on the GPU



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [5]:
# Set random seed


# Check for access to GPU

# Create two random tensors on GPU



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [6]:
# Perform matmul on tensor_A and tensor_B


### 8. Find the maximum and minimum values of the output of 7.

In [7]:
# Find max

# Find min


### 9. Find the maximum and minimum index values of the output of 7.

In [8]:
# Find arg max


# Find arg min



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [9]:
# Set seed


# Create random tensor


# Remove single dimensions


# Print out tensors and their shapes
