In [1]:
!nvidia-smi

Sat Aug 30 12:48:29 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 560.35.03              Driver Version: 560.35.03      CUDA Version: 12.6     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla P100-PCIE-16GB           Off |   00000000:00:04.0 Off |                    0 |
| N/A   36C    P0             26W /  250W |       0MiB /  16384MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

### Check for GPU access with Pytorch

In [2]:
import torch 

torch.cuda.is_available()

True

# Setup device agnostic code
For PyTorch run on GPU if available, else default to CPU

In [3]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device 

'cuda'

In [4]:
# count number of devices 
torch.cuda.device_count()

1

 ## Putting tensors and models on the GPU 
 Using a GPU results in faster computations 

In [5]:
# create a tensor (default on the CPU)
tensor = torch.tensor([1,2,3], device = "cpu")

# tensor not on GPU 
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [6]:
# move tensor to GPU (if available) 
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

## Moving tensors back to the CPU 
if tensor is on GPU, cannot transform it to NumPy

In [7]:
# tensor_on_gpu.numpy()

In [8]:
# to fix the GPU tensor with NumPy issue, we can first set it to the CPU 
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [9]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')